# Generated by Django 5.1.4 on 2025-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_nfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfctag',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nfc',
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
