# Generated by Django 5.1.4 on 2025-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_nfctag_assigned_at_remove_product_nfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='product_audio/'),
        ),
    ]
