# Generated by Django 5.1.4 on 2025-04-13 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_nfctag_assigned_at_alter_nfctag_assigned_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nfc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_product', to='products.nfctag'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='nfctag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='products.product'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
