# Generated by Django 5.1.4 on 2025-04-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_device_remove_nfctag_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_product', to='products.nfctag'),
        ),
    ]
